#!/usr/bin/env php
<?php

use Illuminate\Foundation\Application;
use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

$temporaryDirectory = __DIR__.'/storage/framework/tmp';

if (! is_dir($temporaryDirectory)) {
    mkdir($temporaryDirectory, 0777, true);
}

putenv('TEMP='.$temporaryDirectory);
putenv('TMP='.$temporaryDirectory);
$_ENV['TEMP'] = $temporaryDirectory;
$_ENV['TMP'] = $temporaryDirectory;
$_SERVER['TEMP'] = $temporaryDirectory;
$_SERVER['TMP'] = $temporaryDirectory;

// Register the Composer autoloader...
require __DIR__.'/vendor/autoload.php';

// Bootstrap Laravel and handle the command...
/** @var Application $app */
$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
